package com.fox.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import org.springframework.data.annotation.Id;

import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Set;

/**
 * Created by shuangf on 1/9/18.
 */

@DynamoDBTable(tableName = "QAStatusInfo")
public class QAStatusInfo {

    @Id
    private QAStatusInfoId qaStatusInfoId;

//    private String id;
    private String user;
    private Set<String> update;

//    private String project;
//    Timestamp timeStamp = new Timestamp(System.currentTimeMillis());
//    private String updateDate = String.valueOf(timeStamp.getTime());

    public QAStatusInfo(){}

    public QAStatusInfo(String user, Set<String> update){
        this.user = user;
        this.update = update;

    }

//    @DynamoDBHashKey
//    @DynamoDBAutoGeneratedKey
//    public String getId() {
//        return id;
//    }
//
//    public void setId(String id) {
//        this.id = id;
//    }

    @DynamoDBAttribute(attributeName = "userID")
    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    @DynamoDBAttribute(attributeName = "Update")
    public Set<String> getUpdate() {
        return update;
    }

    public void setUpdate(Set<String> update) {
        this.update = update;
    }

//    @DynamoDBHashKey(attributeName = "Project")
//    public String getProject() {
//        return project;
//    }
//
//    public void setProject(String project) {
//        this.project = project;
//    }
//
//    @DynamoDBRangeKey(attributeName = "TimeStamp")
//    public String getUpdateDate() {
//        return updateDate;
//    }
//
//    public void setUpdateDate(String updateDate) {
//        this.updateDate = updateDate;
//    }


    @DynamoDBHashKey (attributeName = "Project")
    public String getProject() {

        return qaStatusInfoId != null ? qaStatusInfoId.getProject():null;
    }

    public void setProject(String project) {
        if(qaStatusInfoId ==null) {
            qaStatusInfoId = new QAStatusInfoId();
        }
        qaStatusInfoId.setProject(project);
    }




    @DynamoDBRangeKey (attributeName = "TimeStamp")
    public String getUpdateDate() {
        return qaStatusInfoId != null ? qaStatusInfoId.getUpdateDate():null;

    }

    public void setUpdateDate(String updateDate) {
        if(qaStatusInfoId ==null) {
            qaStatusInfoId = new QAStatusInfoId();
        }
        qaStatusInfoId.setUpdateDate(updateDate);
    }






}
